version: "3.3"
services:

 mariadb:
  build:
    context: ./mariadb_docker_dir
    args:
     - buildno
     - gitcommithash
    labels:
     author: james
     other_label: gidday
  deploy:
     restart_policy:
       condition: on-failure
       delay: 5s
       max_attempts: 3
       window: 120s
     resources:
       limits:
         cpus: '1'
         memory: 1G
  environment:
    RACK_ENV: development
    SHOW: 'true'
  logging:
     driver: syslog
     options:
       syslog-address: "tcp://192.168.0.42:123"
  volumes:
       - "dbdata:/var/lib/mysql/data"
  domainname: foo.com
  hostname: foo
 
 phpmyadmin:
   build:
    context: ./phpmyadmin_docker_dir
   depends_on:
    - mysql 
    - wap
   domainname: foo.com
   hostname: foo
   deploy:
    restart_policy:
     condition: on-failure
     delay: 5s
     max_attempts: 3
     window: 120s
      
 wap:
   build:
    context: ./nginx_docker_dir
   deploy:
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s
    resources:
         limits:
           cpus: '1'
           memory: 1G
   ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
   logging:
     driver: syslog
     options:
       syslog-address: "tcp://192.168.0.42:123"
   volumes:
       - "dbdata:/var/lib/mysql/data"
   domainname: foo.com
   hostname: foo
   
