version: "3.3"
services:

 mariadb:
  build:
    context: ./mariadb
    args:
     - buildno
     - gitcommithash
    labels:
     author: james
     other_label: gidday
    sysctls:
      net.core.somaxconn: 1024
  deploy:
     restart_policy:
       condition: on-failure
       delay: 5s
       max_attempts: 3
       window: 120s
     resources:
       limits:
         cpus: '1'
         memory: 1G
  environment:
    RACK_ENV: development
    SHOW: 'true'
  logging:
     driver: syslog
     options:
       syslog-address: "tcp://192.168.0.42:123"
  volumes:
       - "/var/lib/engines/volumes/mariadb/data:/var/lib/mysql/data"
  domainname: engines.internal
  hostname: mariadb
 
 phpmyadmin:
   build:
    context: ./phpmyadmin
   depends_on:
    - mariadb 
    - wap
   domainname: engines.internal
   hostname: phpmyadmin
   deploy:
    restart_policy:
     condition: on-failure
     delay: 5s
     max_attempts: 3
     window: 120s
      
 wap:
   build:
    context: ./wap
   deploy:
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s
    resources:
         limits:
           cpus: '1'
           memory: 1G
   ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
      - target: 443
        published: 4430
        protocol: tcp
        mode: host
   logging:
     driver: syslog
     options:
       syslog-address: "tcp://192.168.0.42:123"
   volumes:
       - "/var/lib/engines/volumes/wap/config:/etc/nginx"
       - "/var/lib/engines/volumes/wap/certs:/etc/nginx/ssl"
   domainname: engines.internal
   hostname: wap
   
